### PR TITLE
Screenshot testing

### PR DESCRIPTION
**Pull request by taylrj**
This commit introduces screenshot testing before commiting files. Applying `puppeteer` to screenshot current pages as below : 

- homepage

- topic listing

- topic landing page

- article listing

- article page

- photo article page

- photography page

Next, `pixelmatch` will compare the screenshots with the ground-truth screenshots by pixel-wise. If number of different pixels are larger than zero, it would fail the test.

### CODE REVIEW

**Comment by taylrj** [comment]
Totally 3 min.

**Comment by taylrj** [comment]
testing_result

**Comment by nickhsine** [comment]
Remember to refine those commits

**Comment by taylrj** [comment]
- Separated ui-test from test for the sake of not running ui-test on circle-ci server
- Run both ui-test and unit test before commiting

**Comment by nickhsine** [comment]
Nice work 🔥 🔥 🔥

**Pull request merged**
