### PR TITLE
Slideshow navigation update and update React version

### PR DESCRIPTION
**Pull request by nickhsine**
Update React is due to [this](https://github.com/facebook/react/pull/7165)

@garfieldduck

### CODE REVIEW

**Comment by garfieldduck** [comment]
LGTM  :shipit:

**Comment by nickhsine** [comment]
@garfieldduck  @hcchien 
照之前說的，增加了 device ，讓需要的 component 可以 render by device。

**Comment by hcchien** [comment]
LGTM

**Comment by garfieldduck** [comment]
:+1:

**Pull request merged**
