### PR TITLE
chore: upgrade babel to ^7.4.0

### PR DESCRIPTION
**Pull request by Aylie-Chou**
- this patch use `npx babel-upgrade --write` to upgrade babel & its dependencies.
- babel [deprecate](https://babeljs.io/docs/en/v7-migration#remove-proposal-polyfills-in-babelpolyfillhttpsgithubcombabelbabelissues8416) `@babel-polyfill` in v7.4.0, and suggest to use `core-js` for polyfill.

### CODE REVIEW

**Comment by taylrj** [comment]
Nice upgrade to babel 7 !!

Actually, I encountered a little issue when checking out this change and ran dev server on localhost.

`Uncaught ReferenceError: regeneratorRuntime is not defined`

Did you bump into the same issue ?

**Comment by Aylie-Chou** [comment]
Dev server is fine on my environment.
Could you help to provide some screenshots or log with the issue ?

**Comment by Aylie-Chou** [comment]
updated ([0aa05a3](https://github.com/twreporter/twreporter-react/pull/2229/commits/0aa05a359f355c69c22f8eb98a7cb1e4b7cd4081))

The `regenerationRuntime` error is caused by @babel/preset-env target setting. To solve it,  `regenerator-runtime` package is imported manually.
ref: [babel issue](https://github.com/babel/babel/issues/9849)

**Review by taylrj — APPROVED** [review]
LGTM 👍

**Pull request merged**
