### PR TITLE
Added the burger menu for #138

### PR DESCRIPTION
**Pull request by garfieldduck**
Added the burger menu for mobile devices with css animations

### CODE REVIEW

**Comment by hcchien** [comment]
I think we should set the logo align to left in mobile device.

**Comment by hcchien** [comment]
it doesn't work in iPhone5.
http://dev.twreporter.org/

**Comment by garfieldduck** [comment]
strange... it works on the chrome web dev console and Note 5. I will borrow an iPhone and take a look later.

**Comment by hcchien** [comment]
btw, I tested it on the Safari of iPhone5.

**Pull request merged**
