### PR TITLE
use react-flex-carousel to replace react-slick

### LINKED ISSUE #113: enlarge the arrow size of the carousel
It's too small for now.

### PR DESCRIPTION
**Pull request by kidwm**
This also fix #113 and other react-slick issues like switching back from other browser tab would make carousel disappear.

### CODE REVIEW

**Comment by nickhsine** [comment]
@kidwm the mobile style seems having a little bit problem.

**Comment by kidwm** [comment]
@nickhsine what is the problem?

**Comment by nickhsine** [comment]
20151206-index-mobile
here is the mockup.
There are two styling issue:
1. the block containing title, description should overlays the image.
2. the dots under the carousel are missing

**Comment by kidwm** [comment]
What does `the block containing title, description should overlays the image.` mean?

**Comment by nickhsine** [comment]
screen shot 2015-12-29 at 11 52 27 am

this block

**Comment by kidwm** [comment]
@nickhsine it should be okay now.

**Comment by nickhsine** [comment]
Looks good :100:  :+1:  :shipit:

**Pull request merged**
