### PR TITLE
chore: bump version to 4.6.7-rc.0

### PR DESCRIPTION
**Pull request by babygoat**

### CODE REVIEW

**Comment by taylrj** [comment]
LGTM

**Comment by babygoat** [comment]
@taylrj  I suggest we should stabilize the commit

Commit generation convention in backend
```
git log --pretty='format:- [[%C(auto)%h](https://github.com/twreporter/twreporter-react/commit/%H)] - %s(%an)' [TAG]...HEAD --no-mergesd
```

**Comment by babygoat** [comment]
I will merge first to test on staging. We can make the final decision before v4.6.7 release.

**Comment by taylrj** [comment]
Currently, front-end repositories (except for monorepo) use [changelog-maker](https://github.com/nodejs/changelog-maker) to generate commits in `CHANGELOG.md`.

The result looks similar to `git log ...` command as above comment. 
Do you suggest we should unify the way generating commits ?

**Comment by babygoat** [comment]
> Currently, front-end repositories (except for monorepo) use [changelog-maker](https://github.com/nodejs/changelog-maker) to generate commits in `CHANGELOG.md`.
> 
> The result looks similar to `git log ...` command as above comment.
> Do you suggest we should unify the way generating commits ?

IMO, it would make the changelog modification and the releaser development easier if we have a unified style. But we don't have to fulfill it in this patch. I could change the format to be consistent with that from changelog-maker. Besides, I strongly suggest removing the merge commit. What do u think?

**Comment by taylrj** [comment]
Sure, I'd like to remove all of the merge commits since they are not necessary and does not provide more information.

**Pull request merged**
